# Указываем, что функции будут находиться в директории "netlify/functions"
[build]
  functions = "netlify/functions"

# Настраиваем перенаправление URL-запросов
[[redirects]]
  # Все запросы, начинающиеся с "/api/", будут перенаправлены
  from = "/api/*"
  # Перенаправляемые запросы будут обрабатываться функциями в директории ".netlify/functions"
  # ":splat" позволяет передать оставшуюся часть URL в функцию
  to = "/.netlify/functions/:splat"
  # Устанавливаем статус перенаправления как 200 (успешный запрос)
  status = 200
